version: '3.8'

services:
  mongo:
    image: mongo
    container_name: netpulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: netpulse-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongo:27017/netpulse
      - JWT_SECRET=your_jwt_secret
      - SCAN_INTERVAL=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: netpulse-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend

volumes:
  mongo_data:
